language: node_js
node_js:
- '6'
env:
  global:
    secure: YVK11CmFg2GBGB6bYa58uPHZh0DD9P3ovqi2xySqq0jbfLghjcAqg2+0q3/wQhwM808nDSHSyYREYa6C8M+Qk0CLUC3qmYiV5DJB/9yCJRPj3Bujug6CLFSBQziy5x2tibhRfUTmgKrwZw6JKwB7ZudzOgpXLbjY582sG3FbWOqqiLsuVk97+uYkNXc0nHUmpOmnPxWnJ9T+P8ZbHU6Knz1QDXkegLoz4D0h0EBOZinTdsGuenjXFl0D2FxDs+MTULFC+4414vdYZpf1JDP8CvGf8s8SvWBmlHcDcqCPuAQqAznRfWZf1E4AiibHH54HLGEbgZgb/JobQ8CDXe7Y5aFJ5+TNPklvGkpCmP3erFweZR53fDbOmyY5ny+splTmJbNqCPjdE8OYYzP07q8nnB1taZtlPzVhfipAKQ2nPLb6hCfE1cDo1xqxakWbpJeccRE+LMIyMa7GItqq5mL32Q4P7VRSoKx2gLsG85rGNEDF2FUDJhbP+9q0PKFzG+FlxuJvuCezWwR6HzbGyL4G7QblCX12oCXXr0UVvVR05yDHMoT/jgvJm7rBomRktaplufv+Tiy/qfapf/nvrtL5CKm1/A/0R0OvzPtQwKtzviiCyi18mnILYQjdP1Ug9Tt4FQ1sLtsX2TWm7tjch/yAooik8kzO5E2f/aTPf2R2Ze0=
