ui: mocha-bdd
browserify:
  - transform:
      name: babelify
      presets: latest
      plugins: add-module-exports
browsers:
  - name: chrome
    version: -1..latest
  - name: firefox
    version: -1..latest
  - name: internet explorer
    version: 11..latest
  - name: android
    version: '4.4..latest'
  - name: safari
    version: 8..latest
  - name: iphone
    version: '8.1..latest'
